agents:
  # program_director removed - using autonomous W/E/R workflow
  content_expert:
    temperature: 0.7
    max_tokens: 32000
    role: "Content writer with web research capabilities"
    specialization: "Academic content creation with current examples"

  education_expert:
    temperature: 0.3
    max_tokens: 32000
    role: "Pedagogical quality assurance and template compliance"
    focus: "WLO alignment and assessment criteria"

  alpha_student:
    temperature: 0.5
    max_tokens: 32000
    role: "Student perspective and usability testing"
    focus: "Clarity, engagement, and practical applicability"

# Quality standards
quality_standards:
  wlo_alignment: "mandatory"
  citation_completeness: "required"
  link_validation: "automatic"
  template_compliance: "strict"
  academic_tone: "professional but accessible"
  building_blocks_compliance: "mandatory"
  accessibility_standards: "required"

# Building Blocks V2 compliance requirements
building_blocks:
  multimedia_requirements:
    figures:
      caption_format: "Figure [#]: [Title]"
      source_required: true
      alt_text_required: true
      in_text_citation: true

    tables:
      caption_format: "Table [#]: [Title]"
      source_required: true
      alt_text_required: true
      in_text_citation: true

    videos:
      duration_preference: "3-5 minutes"
      required_elements: ["title", "url", "duration", "rationale", "accessibility_note"]
      subtitle_requirement: "Must note subtitles/captions availability"

    reading_references:
      integration_methods: ["narrative_incorporation", "clear_signposting"]
      citation_style: "APA"
      signpost_format: "📖 **Reading Reference**: [Title and citation]"

  assessment_standards:
    quiz_requirements:
      question_type_specification: true
      difficulty_levels: ["Easy", "Medium", "Hard"]
      multiple_choice_options: 4  # Always A, B, C, D
      feedback_provision: "where appropriate"
      blackboard_ultra_format: true

# Assessment guidelines
assessment:
  rubric_alignment: "All criteria must map to WLOs"
  grading_scale: "4-point scale preferred"
  feedback_quality: "Specific and actionable"
  quiz_compliance: "Must follow Building Blocks V2 format requirements"

# Accessibility requirements
accessibility:
  alt_text: "Required for all figures and tables"
  video_captions: "Must note availability of subtitles/captions"
  screen_reader_compatibility: "All multimedia elements must be accessible"
  inclusive_design: "Use diverse examples and accessible language"