course:
  title: "Master's Program Weekly Content"
  citation_style: "APA"
  template_version: "AUG_GC_V.2"

# Learning time allocations based on template
learning_phases:
  discovery:
    duration_minutes: 85
    description: "Main content exploration and topic understanding"
  engagement:
    duration_minutes: 85
    description: "Interactive activities and deeper application"
  consolidation:
    duration_minutes: 42
    description: "Knowledge check, reflection, and summary"

# Section-specific requirements
section_requirements:
  overview:
    paragraphs: "1-2"
    guiding_questions: "2-3"
    format: "narrative"

  weekly_learning_outcomes:
    max_wlos: 3
    clo_mapping_required: true
    format: "WLO#: [objective] (CLO1, CLO2)"

  key_words:
    citation_required: true
    format: "Definition + Citation"

  readings_list:
    include_focus_area: true
    include_rationale: true
    include_time_estimate: true
    emoji_format: "🔍 Focus Area, 💡 Rationale, ⏳ Estimated Time"

  engagement_phase:
    activity_types: ["Discussion", "Simulation", "Case Study", "Project"]
    wlo_alignment_required: true
    grading_rubric_required: true

  consolidation_phase:
    quiz_max_questions: 10
    quiz_time_limit_minutes: 20
    quiz_attempts: 1
    reflection_poll_required: true

freshness:
  max_age_days: 730  # 2 years for current content
  keywords_requiring_freshness:
    - "latest"
    - "current"
    - "recent"
    - "new"
    - "2024"
    - "2025"
    - "industry"
    - "trends"
    - "benchmark"
    - "state-of-the-art"
    - "emerging"
    - "cutting-edge"
    - "modern"

web_search:
  default_top_k: 5
  timeout_seconds: 15
  max_redirects: 3
  prefer_academic_sources: true

agents:
  program_director:
    temperature: 0.3
    max_tokens: 2000
    role: "Orchestrator and quality gatekeeper"

  content_expert:
    temperature: 0.7
    max_tokens: 4000
    role: "Content writer with web research capabilities"
    specialization: "Academic content creation with current examples"

  education_expert:
    temperature: 0.3
    max_tokens: 2000
    role: "Pedagogical quality assurance and template compliance"
    focus: "WLO alignment and assessment criteria"

  alpha_student:
    temperature: 0.5
    max_tokens: 2000
    role: "Student perspective and usability testing"
    focus: "Clarity, engagement, and practical applicability"

# Quality standards
quality_standards:
  wlo_alignment: "mandatory"
  citation_completeness: "required"
  link_validation: "automatic"
  template_compliance: "strict"
  academic_tone: "professional but accessible"
  building_blocks_compliance: "mandatory"
  accessibility_standards: "required"

# Building Blocks V2 compliance requirements
building_blocks:
  multimedia_requirements:
    figures:
      caption_format: "Figure [#]: [Title]"
      source_required: true
      alt_text_required: true
      in_text_citation: true

    tables:
      caption_format: "Table [#]: [Title]"
      source_required: true
      alt_text_required: true
      in_text_citation: true

    videos:
      duration_preference: "3-5 minutes"
      required_elements: ["title", "url", "duration", "rationale", "accessibility_note"]
      subtitle_requirement: "Must note subtitles/captions availability"

    reading_references:
      integration_methods: ["narrative_incorporation", "clear_signposting"]
      citation_style: "APA"
      signpost_format: "📖 **Reading Reference**: [Title and citation]"

  assessment_standards:
    quiz_requirements:
      question_type_specification: true
      difficulty_levels: ["Easy", "Medium", "Hard"]
      multiple_choice_options: 4  # Always A, B, C, D
      feedback_provision: "where appropriate"
      blackboard_ultra_format: true

# Assessment guidelines
assessment:
  rubric_alignment: "All criteria must map to WLOs"
  grading_scale: "4-point scale preferred"
  feedback_quality: "Specific and actionable"
  quiz_compliance: "Must follow Building Blocks V2 format requirements"

# Accessibility requirements
accessibility:
  alt_text: "Required for all figures and tables"
  video_captions: "Must note availability of subtitles/captions"
  screen_reader_compatibility: "All multimedia elements must be accessible"
  inclusive_design: "Use diverse examples and accessible language"