# Template Mapping for Weekly Content Template AUG_GC_V.2
# This file maps template requirements to implementation details
# Structure: 1.Overview, 2.DISCOVERY, 3.ENGAGEMENT, 4.CONSOLIDATION

template_info:
  name: "Weekly_Content_Template_AUG_GC_V.2"
  version: "2.0"
  source: "Academic Course Design Template"

# Section-specific implementation guidelines (aligned with template.md structure)
sections:
  "01-overview":
    template_name: "Section 1: Overview"
    template_requirements:
      - "Complete overview section containing all 5 subsections"
      - "1.1 Introduction: 1-2 paragraphs overview + 2-3 guiding questions"
      - "1.2 Weekly Level Learning Outcomes: ~3 WLOs with CLO mapping"
      - "1.3 Key Words: definitions with proper citations"
      - "1.4 Learning Activities: summary table (to be completed at end)"
      - "1.5 Readings List: with focus areas, rationale, time estimates"
    implementation:
      heading_level: "H2"
      subsections:
        introduction:
          content: "1-2 paragraphs overview + 2-3 intriguing/challenging questions"
          format: "narrative"
        wlos:
          content: "~3 Weekly Learning Outcomes with CLO mapping"
          format: "WLO1: [objective] (CLO1, CLO2)"
          alignment_required: true
        keywords:
          content: "Main terminology with definitions and citations"
          format: "1. Term\\nDefinition: ...\\nCitation: ..."
          citation_required: true
        learning_activities:
          content: "Summary table of all activities (Discovery 85min + Engagement 85min + Consolidation 42min)"
          note: "Complete at end of content production"
        readings_list:
          content: "Required and supplemental materials"
          format: "Source\\n🔍 Focus Area: ...\\n💡 Rationale: ...\\n⏳ Estimated Time: ..."
          citation_style: "academic_reference"

  "02-discovery":
    template_name: "Section 2: DISCOVERY (85 minutes)"
    template_requirements:
      - "Main learning content with topics, narratives, readings, activities, and assessment hints"
      - "85 minutes total active learning time"
      - "Multiple topics possible - copy structure for each"
      - "Narrative content with real-world examples"
      - "Reference readings integrated within narrative flow"
      - "Interactive activities (drag-drop, matching, etc.)"
      - "Assessment Hints section highlighting exam-relevant content"
    implementation:
      heading_level: "H2"
      duration: 85
      structure:
        - "Topic Title(s) (e.g., Topic 1: Change or Transformation?)"
        - "Narrative content (explanatory text with examples)"
        - "Reading references (integrated within narrative)"
        - "Interactive activities (drag-drop, matching, etc.)"
        - "Assessment Hints (guidance for exam preparation)"
      content_guidelines:
        topics: "Multiple topics possible - copy structure for each"
        narrative_style: "Educational, engaging, with real-world examples"
        reading_integration: "Reference readings within narrative flow"
        activities: "Interactive elements to reinforce learning"
        assessment_hints: "Separate section highlighting exam-relevant content"
      examples:
        - "Position elements under change vs transformation"
        - "Click on results to see if choices are correct"
        - "Pool of words matching exercises"

  "03-engagement":
    template_name: "Section 3: ENGAGEMENT (85 minutes)"
    template_requirements:
      - "Graded interactive learning activities aligned with WLOs"
      - "85 minutes total active learning time"
      - "Activity Title (descriptive name)"
      - "Activity Type (Discussion/Simulation/Case Study/Project)"
      - "Aligned Weekly Level Learning Outcome (WLO)"
      - "Instructions for Students (detailed guidance)"
      - "Grading Rubric (assessment criteria)"
    implementation:
      heading_level: "H2"
      duration: 85
      structure:
        - "Activity Title (descriptive name)"
        - "Activity Type (Discussion/Simulation/Case Study/Project)"
        - "Aligned Weekly Level Learning Outcome (WLO)"
        - "Instructions for Students (detailed guidance)"
        - "Grading Rubric (assessment criteria)"
      activity_requirements:
        graded: true
        wlo_alignment_explicit: true
        student_instructions: "Clear, detailed guidance including preparation requirements"
        rubric_detailed: "Specific assessment criteria and standards"
      activity_types: ["Discussion", "Simulation", "Case Study", "Project"]
      note: "Recommend completing Discovery phase before engagement"

  "04-consolidation":
    template_name: "Section 4: CONSOLIDATION (42 minutes)"
    template_requirements:
      - "Knowledge check quiz, reflection poll, and weekly summary with forward look"
      - "42 minutes total time"
      - "Knowledge Check (quiz with multiple question types)"
      - "Reflection Poll (standardized self-assessment questions)"
      - "Summary and Looking Ahead (week recap + next week preview)"
    implementation:
      heading_level: "H2"
      duration: 42
      structure:
        - "Knowledge Check (quiz with multiple question types) written as numbered list"
        - "Reflection Poll (standardized self-assessment questions)"
        - "Summary and Looking Ahead (week recap + next week preview)"
      quiz_specifications:
        total_questions: "Maximum 10 questions"
        attempts: "1 (one)"
        time_limit: "20 minutes"
        question_sources: "Use Building Blocks document for question templates"
      reflection_poll:
        time_spent: "Less than 1 hour / 1-3 hours / 3-5 hours / More than 5 hours"
        understanding: "4-point scale from lost to fully confident"
        study_improvements: "Multiple choice options for next week changes"
      summary_format: "1 paragraph current week + 1 paragraph next week preparation"

# Standard reflection poll questions from template
standard_reflection_questions:
  - question: "How much time did you spend engaging with the course materials this week?"
    options:
      - "Less than 1 hour"
      - "1–3 hours"
      - "3–5 hours"
      - "More than 5 hours"

  - question: "How well do you think you understand the key concepts from this week's material?"
    options:
      - "I feel lost and need significant help"
      - "I understand parts of it but need more review"
      - "I mostly understand but could use some clarification"
      - "I fully understand and feel confident applying it"

  - question: "What is one change you plan to make in your study habits next week to improve your learning?"
    options:
      - "Spend more time engaging with the content"
      - "Engage more actively with activities"
      - "Take better notes or review materials more often"
      - "Seek clarification when needed"
      - "Find a quieter place to study with fewer distractions"
      - "No changes—I'm happy with my approach"

# Time allocation guidelines
time_allocations:
  discovery_phase: 85  # minutes
  engagement_phase: 85  # minutes
  consolidation_phase: 42  # minutes
  total_learning_time: 212  # minutes (~3.5 hours)

# Quality checks specific to template
template_compliance_checks:
  - "All three phases (Discovery, Engagement, Consolidation) present"
  - "Time allocations match template requirements"
  - "WLO alignment explicitly stated in Engagement phase"
  - "Grading rubric present for graded activities"
  - "Reflection poll uses standard questions"
  - "Knowledge check has ≤10 questions, 20-minute limit, 1 attempt"
  - "Citations follow academic format"
  - "Emoji format used in readings list"